'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EN_UK
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LibreriaGrafica.EN-UK", GetType(EN_UK).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Degree Passage Project - EMT 
        '''Escuela superior de informática.
        '''</summary>
        Friend Shared ReadOnly Property AcercaDe_desc() As String
            Get
                Return ResourceManager.GetString("AcercaDe_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logistics and automotive traceability system.
        '''</summary>
        Friend Shared ReadOnly Property AcercaDe_lbltitle() As String
            Get
                Return ResourceManager.GetString("AcercaDe_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Project Letter.
        '''</summary>
        Friend Shared ReadOnly Property AcercaDe_link_letra() As String
            Get
                Return ResourceManager.GetString("AcercaDe_link_letra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alert!.
        '''</summary>
        Friend Shared ReadOnly Property Alerta() As String
            Get
                Return ResourceManager.GetString("Alerta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save.
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_btn_guardar() As String
            Get
                Return ResourceManager.GetString("AltaUser_btn_guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Last name:.
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_lbl_ape() As String
            Get
                Return ResourceManager.GetString("AltaUser_lbl_ape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mobile:.
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_lbl_cel() As String
            Get
                Return ResourceManager.GetString("AltaUser_lbl_cel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name:.
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_lbl_name() As String
            Get
                Return ResourceManager.GetString("AltaUser_lbl_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password:.
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_lbl_pass() As String
            Get
                Return ResourceManager.GetString("AltaUser_lbl_pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone:.
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_lbl_tel() As String
            Get
                Return ResourceManager.GetString("AltaUser_lbl_tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User:.
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_lbl_username() As String
            Get
                Return ResourceManager.GetString("AltaUser_lbl_username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User entered correctly..
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_usuario_ingresado() As String
            Get
                Return ResourceManager.GetString("AltaUser_usuario_ingresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You must fill in all fields and there cannot be 2 equal users..
        '''</summary>
        Friend Shared ReadOnly Property AltaUser_usuario_vacios_duplicado() As String
            Get
                Return ResourceManager.GetString("AltaUser_usuario_vacios_duplicado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_btnCrear() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_btnCrear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Year.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_lblanio() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_lblanio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Color.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_lblcolor() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_lblcolor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Brand.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_lblmarca() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_lblmarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Model.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_lblmodelo() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_lblmodelo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Type.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_lbltipo() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_lbltipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicle registration.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_lbltitle() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a VIN.
        '''</summary>
        Friend Shared ReadOnly Property AltaVehiculo_lblvin() As String
            Get
                Return ResourceManager.GetString("AltaVehiculo_lblvin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sign In.
        '''</summary>
        Friend Shared ReadOnly Property ButtonLogin() As String
            Get
                Return ResourceManager.GetString("ButtonLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Standard car.
        '''</summary>
        Friend Shared ReadOnly Property CambiarImagenTipo_StandardCar() As String
            Get
                Return ResourceManager.GetString("CambiarImagenTipo_StandardCar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Truck.
        '''</summary>
        Friend Shared ReadOnly Property CambiarImagenTipo_Truck() As String
            Get
                Return ResourceManager.GetString("CambiarImagenTipo_Truck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change.
        '''</summary>
        Friend Shared ReadOnly Property CambioPass_btnCambiar() As String
            Get
                Return ResourceManager.GetString("CambioPass_btnCambiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New password.
        '''</summary>
        Friend Shared ReadOnly Property CambioPass_lblnewPass() As String
            Get
                Return ResourceManager.GetString("CambioPass_lblnewPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Current password.
        '''</summary>
        Friend Shared ReadOnly Property CambioPass_lbloldPass() As String
            Get
                Return ResourceManager.GetString("CambioPass_lbloldPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change of password.
        '''</summary>
        Friend Shared ReadOnly Property CambioPass_lbltitle() As String
            Get
                Return ResourceManager.GetString("CambioPass_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Empty fields.
        '''</summary>
        Friend Shared ReadOnly Property CamposVacios() As String
            Get
                Return ResourceManager.GetString("CamposVacios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a About.
        '''</summary>
        Friend Shared ReadOnly Property ConfigBoton_acercaDe() As String
            Get
                Return ResourceManager.GetString("ConfigBoton_acercaDe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change of password.
        '''</summary>
        Friend Shared ReadOnly Property ConfigBoton_cambiarPass() As String
            Get
                Return ResourceManager.GetString("ConfigBoton_cambiarPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Graphic options.
        '''</summary>
        Friend Shared ReadOnly Property ConfigBoton_configGrafica() As String
            Get
                Return ResourceManager.GetString("ConfigBoton_configGrafica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Network Configuration.
        '''</summary>
        Friend Shared ReadOnly Property ConfigBoton_configRed() As String
            Get
                Return ResourceManager.GetString("ConfigBoton_configRed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Settings.
        '''</summary>
        Friend Shared ReadOnly Property ConfigBoton_configTitle() As String
            Get
                Return ResourceManager.GetString("ConfigBoton_configTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Language.
        '''</summary>
        Friend Shared ReadOnly Property ConfigBoton_lenguaje() As String
            Get
                Return ResourceManager.GetString("ConfigBoton_lenguaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apply.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_applyText() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_applyText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apply.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_applyTma() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_applyTma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Graphic configuration.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_lbltitle() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Theme.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_lbltma() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_lbltma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Text size:.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_lbltxt() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_lbltxt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a White.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_opcClaro() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_opcClaro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dark.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_opcNight() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_opcNight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reset.
        '''</summary>
        Friend Shared ReadOnly Property ConfigGrafica_reset() As String
            Get
                Return ResourceManager.GetString("ConfigGrafica_reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Language.
        '''</summary>
        Friend Shared ReadOnly Property ConfigIdioma_lbltitle() As String
            Get
                Return ResourceManager.GetString("ConfigIdioma_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_cambiar() As String
            Get
                Return ResourceManager.GetString("ConfigRed_cambiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connect.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_conectar() As String
            Get
                Return ResourceManager.GetString("ConfigRed_conectar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Read error.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_error_lectura() As String
            Get
                Return ResourceManager.GetString("ConfigRed_error_lectura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Database:.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_lblbbdd() As String
            Get
                Return ResourceManager.GetString("ConfigRed_lblbbdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Without this data you will not be able to connect to the server and you will not be able to access the data. If you have any doubts, consult a technician..
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_lblinfo() As String
            Get
                Return ResourceManager.GetString("ConfigRed_lblinfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password:.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_lblpass() As String
            Get
                Return ResourceManager.GetString("ConfigRed_lblpass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Path:.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_lblruta() As String
            Get
                Return ResourceManager.GetString("ConfigRed_lblruta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DSN File:.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_lbltitle() As String
            Get
                Return ResourceManager.GetString("ConfigRed_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User:.
        '''</summary>
        Friend Shared ReadOnly Property ConfigRed_lbluser() As String
            Get
                Return ResourceManager.GetString("ConfigRed_lbluser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Damage_btncancelar() As String
            Get
                Return ResourceManager.GetString("Damage_btncancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add image.
        '''</summary>
        Friend Shared ReadOnly Property Damage_btnimg() As String
            Get
                Return ResourceManager.GetString("Damage_btnimg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ready.
        '''</summary>
        Friend Shared ReadOnly Property Damage_btnlisto() As String
            Get
                Return ResourceManager.GetString("Damage_btnlisto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You must enter something in the description.
        '''</summary>
        Friend Shared ReadOnly Property Damage_descripcion_vacio() As String
            Get
                Return ResourceManager.GetString("Damage_descripcion_vacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New damage.
        '''</summary>
        Friend Shared ReadOnly Property Damage_lbldamage() As String
            Get
                Return ResourceManager.GetString("Damage_lbldamage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description (máx. 255 Caracters).
        '''</summary>
        Friend Shared ReadOnly Property Damage_lbldesc() As String
            Get
                Return ResourceManager.GetString("Damage_lbldesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Damage Information #.
        '''</summary>
        Friend Shared ReadOnly Property DatosDamage_infoDaño() As String
            Get
                Return ResourceManager.GetString("DatosDamage_infoDaño", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Details:.
        '''</summary>
        Friend Shared ReadOnly Property DatosDamage_lbldetalles() As String
            Get
                Return ResourceManager.GetString("DatosDamage_lbldetalles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Information about inspection #.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspecc_info() As String
            Get
                Return ResourceManager.GetString("DatosInspecc_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Damage.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspecc_lbldamage() As String
            Get
                Return ResourceManager.GetString("DatosInspecc_lbldamage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Moment of realization:.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspecc_lbldate() As String
            Get
                Return ResourceManager.GetString("DatosInspecc_lbldate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Place:.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspecc_lbllug() As String
            Get
                Return ResourceManager.GetString("DatosInspecc_lbllug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Responsable:.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspecc_lbluser() As String
            Get
                Return ResourceManager.GetString("DatosInspecc_lbluser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No damage was determined in this inspection..
        '''</summary>
        Friend Shared ReadOnly Property DatosInspecc_lblvacio() As String
            Get
                Return ResourceManager.GetString("DatosInspecc_lblvacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspeccion_btncancelar() As String
            Get
                Return ResourceManager.GetString("DatosInspeccion_btncancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspeccion_btnguardar() As String
            Get
                Return ResourceManager.GetString("DatosInspeccion_btnguardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Damage.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspeccion_btnnewdamage() As String
            Get
                Return ResourceManager.GetString("DatosInspeccion_btnnewdamage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Damage: .
        '''</summary>
        Friend Shared ReadOnly Property DatosInspeccion_daño() As String
            Get
                Return ResourceManager.GetString("DatosInspeccion_daño", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Inspection Saved.
        '''</summary>
        Friend Shared ReadOnly Property DatosInspeccion_guardadoExitoso() As String
            Get
                Return ResourceManager.GetString("DatosInspeccion_guardadoExitoso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a If the vehicle is not damaged, simply save the inspection..
        '''</summary>
        Friend Shared ReadOnly Property DatosInspeccion_lbldamagetext() As String
            Get
                Return ResourceManager.GetString("DatosInspeccion_lbldamagetext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicle inspection: .
        '''</summary>
        Friend Shared ReadOnly Property DatosInspeccion_lbltitleinspec() As String
            Get
                Return ResourceManager.GetString("DatosInspeccion_lbltitleinspec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Surname.
        '''</summary>
        Friend Shared ReadOnly Property DatosUser_lblApellido() As String
            Get
                Return ResourceManager.GetString("DatosUser_lblApellido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cellphone.
        '''</summary>
        Friend Shared ReadOnly Property DatosUser_lblMovil() As String
            Get
                Return ResourceManager.GetString("DatosUser_lblMovil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Password.
        '''</summary>
        Friend Shared ReadOnly Property DatosUser_lblNewPass() As String
            Get
                Return ResourceManager.GetString("DatosUser_lblNewPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property DatosUser_lblNombre() As String
            Get
                Return ResourceManager.GetString("DatosUser_lblNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone.
        '''</summary>
        Friend Shared ReadOnly Property DatosUser_lblTelFijo() As String
            Get
                Return ResourceManager.GetString("DatosUser_lblTelFijo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Print.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_btnprint() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_btnprint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure that you want to delete this vehicle?.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_Delete() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Information of:.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_info() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Color:.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_lblcolor() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_lblcolor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Inspections.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_lblinspecctitle() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_lblinspecctitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Location.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_lbllocation() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_lbllocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Brand:.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_lblmarca() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_lblmarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Model:.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_lblmodelo() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_lblmodelo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This vehicle still has no inspections..
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_lblvacio() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_lblvacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Year:.
        '''</summary>
        Friend Shared ReadOnly Property DatosVehiculo_lblyear() As String
            Get
                Return ResourceManager.GetString("DatosVehiculo_lblyear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wrong username or password.
        '''</summary>
        Friend Shared ReadOnly Property ErrorMsg() As String
            Get
                Return ResourceManager.GetString("ErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Scan.
        '''</summary>
        Friend Shared ReadOnly Property EscanerQR_btnscan() As String
            Get
                Return ResourceManager.GetString("EscanerQR_btnscan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Scanned code! Message:.
        '''</summary>
        Friend Shared ReadOnly Property EscanerQR_codigoEscaneado() As String
            Get
                Return ResourceManager.GetString("EscanerQR_codigoEscaneado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a QR not detected, try again.
        '''</summary>
        Friend Shared ReadOnly Property EscanerQR_errorEscaneo() As String
            Get
                Return ResourceManager.GetString("EscanerQR_errorEscaneo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Point to the QR code and press &apos;Scan&apos;.
        '''</summary>
        Friend Shared ReadOnly Property EscanerQR_meText() As String
            Get
                Return ResourceManager.GetString("EscanerQR_meText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Import vehicles.
        '''</summary>
        Friend Shared ReadOnly Property Funcion_main_importarcsv() As String
            Get
                Return ResourceManager.GetString("Funcion_main_importarcsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start trip.
        '''</summary>
        Friend Shared ReadOnly Property Funcion_main_iniciarviaje() As String
            Get
                Return ResourceManager.GetString("Funcion_main_iniciarviaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Checks.
        '''</summary>
        Friend Shared ReadOnly Property Funcion_main_inspecciones() As String
            Get
                Return ResourceManager.GetString("Funcion_main_inspecciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Batchs.
        '''</summary>
        Friend Shared ReadOnly Property Funcion_main_lotes() As String
            Get
                Return ResourceManager.GetString("Funcion_main_lotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Users.
        '''</summary>
        Friend Shared ReadOnly Property Funcion_main_users() As String
            Get
                Return ResourceManager.GetString("Funcion_main_users", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicles.
        '''</summary>
        Friend Shared ReadOnly Property Funcion_main_vehiculos() As String
            Get
                Return ResourceManager.GetString("Funcion_main_vehiculos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sectors.
        '''</summary>
        Friend Shared ReadOnly Property Funcion_main_zonas() As String
            Get
                Return ResourceManager.GetString("Funcion_main_zonas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Saved..
        '''</summary>
        Friend Shared ReadOnly Property Guardado() As String
            Get
                Return ResourceManager.GetString("Guardado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select File.
        '''</summary>
        Friend Shared ReadOnly Property ImportarVehiculos_btn_cargar() As String
            Get
                Return ResourceManager.GetString("ImportarVehiculos_btn_cargar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save into the system.
        '''</summary>
        Friend Shared ReadOnly Property ImportarVehiculos_btn_cargarBD() As String
            Get
                Return ResourceManager.GetString("ImportarVehiculos_btn_cargarBD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a One or more vehicles were omitted because they already exist in the database.
        '''</summary>
        Friend Shared ReadOnly Property ImportarVehiculos_Error_duplicados_en_BBDD() As String
            Get
                Return ResourceManager.GetString("ImportarVehiculos_Error_duplicados_en_BBDD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Print.
        '''</summary>
        Friend Shared ReadOnly Property InfoLote_btnprint() As String
            Get
                Return ResourceManager.GetString("InfoLote_btnprint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Information from batch: #.
        '''</summary>
        Friend Shared ReadOnly Property InfoLote_info() As String
            Get
                Return ResourceManager.GetString("InfoLote_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicles in the lot: .
        '''</summary>
        Friend Shared ReadOnly Property InfoLote_lbl_inspecctitle() As String
            Get
                Return ResourceManager.GetString("InfoLote_lbl_inspecctitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property InfoLote_lbldesc() As String
            Get
                Return ResourceManager.GetString("InfoLote_lbldesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lot Name: .
        '''</summary>
        Friend Shared ReadOnly Property InfoLote_lblname() As String
            Get
                Return ResourceManager.GetString("InfoLote_lblname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Responsible: .
        '''</summary>
        Friend Shared ReadOnly Property InfoLote_lblusername() As String
            Get
                Return ResourceManager.GetString("InfoLote_lblusername", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Batch: #.
        '''</summary>
        Friend Shared ReadOnly Property InfoLote_nrolote() As String
            Get
                Return ResourceManager.GetString("InfoLote_nrolote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start trip.
        '''</summary>
        Friend Shared ReadOnly Property IniciarViaje_btnNext() As String
            Get
                Return ResourceManager.GetString("IniciarViaje_btnNext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Information: .
        '''</summary>
        Friend Shared ReadOnly Property IniciarViaje_informacion() As String
            Get
                Return ResourceManager.GetString("IniciarViaje_informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Begin a trip.
        '''</summary>
        Friend Shared ReadOnly Property IniciarViaje_lbltitle() As String
            Get
                Return ResourceManager.GetString("IniciarViaje_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You must select one or more lots according to the availability of your previously selected means of transport.
        '''</summary>
        Friend Shared ReadOnly Property IniciarViaje_subtitulo() As String
            Get
                Return ResourceManager.GetString("IniciarViaje_subtitulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List of means of transport.
        '''</summary>
        Friend Shared ReadOnly Property ListadoMediosTransporte_lbltitle() As String
            Get
                Return ResourceManager.GetString("ListadoMediosTransporte_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List of all zones.
        '''</summary>
        Friend Shared ReadOnly Property ListadoZonas_lbltitle() As String
            Get
                Return ResourceManager.GetString("ListadoZonas_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Configuration file load failed, see settings.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_ErrorConexion() As String
            Get
                Return ResourceManager.GetString("LoginVariable_ErrorConexion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Network error, check Network configuration Code:.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_errorRed() As String
            Get
                Return ResourceManager.GetString("LoginVariable_errorRed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connection failed.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_errorRedTitle() As String
            Get
                Return ResourceManager.GetString("LoginVariable_errorRedTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Import from CSV.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_importarCSV() As String
            Get
                Return ResourceManager.GetString("LoginVariable_importarCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log in.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_ingresar() As String
            Get
                Return ResourceManager.GetString("LoginVariable_ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start trip.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_iniciarViaje() As String
            Get
                Return ResourceManager.GetString("LoginVariable_iniciarViaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Inspections.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_inspecciones() As String
            Get
                Return ResourceManager.GetString("LoginVariable_inspecciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Good afternoon,.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_lbl_welcome_afternoon() As String
            Get
                Return ResourceManager.GetString("LoginVariable_lbl_welcome_afternoon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Good morning,.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_lbl_welcome_morning() As String
            Get
                Return ResourceManager.GetString("LoginVariable_lbl_welcome_morning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Good afternoon,.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_lbl_welcome_night() As String
            Get
                Return ResourceManager.GetString("LoginVariable_lbl_welcome_night", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Batches.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_lotes() As String
            Get
                Return ResourceManager.GetString("LoginVariable_lotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Users.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_usuarios() As String
            Get
                Return ResourceManager.GetString("LoginVariable_usuarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You must enter a username and password.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_vacio() As String
            Get
                Return ResourceManager.GetString("LoginVariable_vacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fill the blanks.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_vaciotitle() As String
            Get
                Return ResourceManager.GetString("LoginVariable_vaciotitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicles.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_vehiculos() As String
            Get
                Return ResourceManager.GetString("LoginVariable_vehiculos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Zones.
        '''</summary>
        Friend Shared ReadOnly Property LoginVariable_zonas() As String
            Get
                Return ResourceManager.GetString("LoginVariable_zonas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Batches.
        '''</summary>
        Friend Shared ReadOnly Property MenuLotes_lbltitle() As String
            Get
                Return ResourceManager.GetString("MenuLotes_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log out.
        '''</summary>
        Friend Shared ReadOnly Property MenuPrincipal_cerrarSesion() As String
            Get
                Return ResourceManager.GetString("MenuPrincipal_cerrarSesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Main Menu.
        '''</summary>
        Friend Shared ReadOnly Property MenuPrincipal_titulo() As String
            Get
                Return ResourceManager.GetString("MenuPrincipal_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select an option.
        '''</summary>
        Friend Shared ReadOnly Property MenuVariable_lblSeleccionar() As String
            Get
                Return ResourceManager.GetString("MenuVariable_lblSeleccionar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search by QR.
        '''</summary>
        Friend Shared ReadOnly Property MenuVehiculos_buscarQR() As String
            Get
                Return ResourceManager.GetString("MenuVehiculos_buscarQR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search by VIN.
        '''</summary>
        Friend Shared ReadOnly Property MenuVehiculos_buscarVIN() As String
            Get
                Return ResourceManager.GetString("MenuVehiculos_buscarVIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No vehicles were found with the specified VIN.
        '''</summary>
        Friend Shared ReadOnly Property MenuVehiculos_error_encontrar_vin() As String
            Get
                Return ResourceManager.GetString("MenuVehiculos_error_encontrar_vin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicles.
        '''</summary>
        Friend Shared ReadOnly Property MenuVehiculos_lbltitle() As String
            Get
                Return ResourceManager.GetString("MenuVehiculos_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Scan error.
        '''</summary>
        Friend Shared ReadOnly Property MenuVehicuos_error_escaneo() As String
            Get
                Return ResourceManager.GetString("MenuVehicuos_error_escaneo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check by QR code.
        '''</summary>
        Friend Shared ReadOnly Property NuevaInspeccion_btn_qr1() As String
            Get
                Return ResourceManager.GetString("NuevaInspeccion_btn_qr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check by VIN code.
        '''</summary>
        Friend Shared ReadOnly Property NuevaInspeccion_btn_vin() As String
            Get
                Return ResourceManager.GetString("NuevaInspeccion_btn_vin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check by QR code.
        '''</summary>
        Friend Shared ReadOnly Property NuevaInspeccion_btnQR() As String
            Get
                Return ResourceManager.GetString("NuevaInspeccion_btnQR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check by VIN code.
        '''</summary>
        Friend Shared ReadOnly Property NuevaInspeccion_btnVIN() As String
            Get
                Return ResourceManager.GetString("NuevaInspeccion_btnVIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check a vehicle.
        '''</summary>
        Friend Shared ReadOnly Property NuevaInspeccion_Title() As String
            Get
                Return ResourceManager.GetString("NuevaInspeccion_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create.
        '''</summary>
        Friend Shared ReadOnly Property NuevaSubZona_btnCrear() As String
            Get
                Return ResourceManager.GetString("NuevaSubZona_btnCrear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Capacity.
        '''</summary>
        Friend Shared ReadOnly Property NuevaSubZona_lblcapacidad() As String
            Get
                Return ResourceManager.GetString("NuevaSubZona_lblcapacidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property NuevaSubZona_lbldescripcion() As String
            Get
                Return ResourceManager.GetString("NuevaSubZona_lbldescripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property NuevaSubZona_lblnombre() As String
            Get
                Return ResourceManager.GetString("NuevaSubZona_lblnombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Subzone Creation.
        '''</summary>
        Friend Shared ReadOnly Property NuevaSubZona_lbltitle() As String
            Get
                Return ResourceManager.GetString("NuevaSubZona_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Belonging area.
        '''</summary>
        Friend Shared ReadOnly Property NuevaSubZona_lblzonaPerteneciente() As String
            Get
                Return ResourceManager.GetString("NuevaSubZona_lblzonaPerteneciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_btncancelar() As String
            Get
                Return ResourceManager.GetString("NuevoLote_btncancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Undo.
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_btndeshacer() As String
            Get
                Return ResourceManager.GetString("NuevoLote_btndeshacer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save.
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_btnsave() As String
            Get
                Return ResourceManager.GetString("NuevoLote_btnsave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There are no vehicles to add to lots, these are not inspected or are already in a lot..
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_EmptyVehicle() As String
            Get
                Return ResourceManager.GetString("NuevoLote_EmptyVehicle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select the vehicles to add.
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_lbladdtitle() As String
            Get
                Return ResourceManager.GetString("NuevoLote_lbladdtitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmed Vehicles.
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_lblconfirmados() As String
            Get
                Return ResourceManager.GetString("NuevoLote_lblconfirmados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_lbldesc() As String
            Get
                Return ResourceManager.GetString("NuevoLote_lbldesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_lblnombre() As String
            Get
                Return ResourceManager.GetString("NuevoLote_lblnombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Batch No: .
        '''</summary>
        Friend Shared ReadOnly Property NuevoLote_lblnrolote() As String
            Get
                Return ResourceManager.GetString("NuevoLote_lblnrolote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save.
        '''</summary>
        Friend Shared ReadOnly Property NuevoMedioTransporte_btnsave() As String
            Get
                Return ResourceManager.GetString("NuevoMedioTransporte_btnsave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Capacity.
        '''</summary>
        Friend Shared ReadOnly Property NuevoMedioTransporte_lblcapacidad() As String
            Get
                Return ResourceManager.GetString("NuevoMedioTransporte_lblcapacidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enrollment.
        '''</summary>
        Friend Shared ReadOnly Property NuevoMedioTransporte_lblmatricula() As String
            Get
                Return ResourceManager.GetString("NuevoMedioTransporte_lblmatricula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number.
        '''</summary>
        Friend Shared ReadOnly Property NuevoMedioTransporte_lblnumero() As String
            Get
                Return ResourceManager.GetString("NuevoMedioTransporte_lblnumero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enter means of transport.
        '''</summary>
        Friend Shared ReadOnly Property NuevoMedioTransporte_lbltitle() As String
            Get
                Return ResourceManager.GetString("NuevoMedioTransporte_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property Pass() As String
            Get
                Return ResourceManager.GetString("Pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ready.
        '''</summary>
        Friend Shared ReadOnly Property Ready() As String
            Get
                Return ResourceManager.GetString("Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reset your password.
        '''</summary>
        Friend Shared ReadOnly Property ResetPass() As String
            Get
                Return ResourceManager.GetString("ResetPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Request Change.
        '''</summary>
        Friend Shared ReadOnly Property RestablecerPass_btnSolicitar() As String
            Get
                Return ResourceManager.GetString("RestablecerPass_btnSolicitar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a If you have forgotten your password this window will send a request to the administrator.
        '''</summary>
        Friend Shared ReadOnly Property RestablecerPass_lblsubtitle() As String
            Get
                Return ResourceManager.GetString("RestablecerPass_lblsubtitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Request password change.
        '''</summary>
        Friend Shared ReadOnly Property RestablecerPass_lbltitle() As String
            Get
                Return ResourceManager.GetString("RestablecerPass_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username.
        '''</summary>
        Friend Shared ReadOnly Property RestablecerPass_lblusername() As String
            Get
                Return ResourceManager.GetString("RestablecerPass_lblusername", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You must select at least one batch, and it cannot exced the carriage capacity.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionarLote_errorcapacidad() As String
            Get
                Return ResourceManager.GetString("SeleccionarLote_errorcapacidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Switch to the transport window.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionarLote_lblProgress() As String
            Get
                Return ResourceManager.GetString("SeleccionarLote_lblProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Continue →.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionarMedio_btnNext() As String
            Get
                Return ResourceManager.GetString("SeleccionarMedio_btnNext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Information: .
        '''</summary>
        Friend Shared ReadOnly Property SeleccionarMedio_informacion() As String
            Get
                Return ResourceManager.GetString("SeleccionarMedio_informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a First, select a carriage medium.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionarMedio_lbl_title() As String
            Get
                Return ResourceManager.GetString("SeleccionarMedio_lbl_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select a means of transport, which will determine which lots you can carry according to your capacity..
        '''</summary>
        Friend Shared ReadOnly Property SeleccionarMedio_subtitulo() As String
            Get
                Return ResourceManager.GetString("SeleccionarMedio_subtitulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ready.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionVehiculo_btnready() As String
            Get
                Return ResourceManager.GetString("SeleccionVehiculo_btnready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select the vehicle (s) to move and then ready.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionVehiculo_lblsubtitle() As String
            Get
                Return ResourceManager.GetString("SeleccionVehiculo_lblsubtitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicle Selection.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionVehiculo_lbltitle() As String
            Get
                Return ResourceManager.GetString("SeleccionVehiculo_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select the area to which the vehicle or vehicles will be moved.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionZona_lblsubtitle() As String
            Get
                Return ResourceManager.GetString("SeleccionZona_lblsubtitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Zones.
        '''</summary>
        Friend Shared ReadOnly Property SeleccionZona_lbltitle() As String
            Get
                Return ResourceManager.GetString("SeleccionZona_lbltitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username.
        '''</summary>
        Friend Shared ReadOnly Property UserName() As String
            Get
                Return ResourceManager.GetString("UserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Center map.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_btnCentrarMapa() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_btnCentrarMapa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a See destination.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_btnVerDestino() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_btnVerDestino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Carriage:.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_Coche() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_Coche", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GPS error, do you want to retry?.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_errorGPS() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_errorGPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finish trip.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_FinalizarViaje() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_FinalizarViaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Batch:.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_Lote() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_Lote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User:.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_Usuario() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_Usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vehicles:.
        '''</summary>
        Friend Shared ReadOnly Property ViajeEnCurso_Vehiculos() As String
            Get
                Return ResourceManager.GetString("ViajeEnCurso_Vehiculos", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
