'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ErrorCodes
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LibreriaGrafica.ErrorCodes", GetType(ErrorCodes).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00006.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCamposVacios() As String
            Get
                Return ResourceManager.GetString("ErrorCamposVacios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00008.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCargaBD() As String
            Get
                Return ResourceManager.GetString("ErrorCargaBD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00006.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCargarImg() As String
            Get
                Return ResourceManager.GetString("ErrorCargarImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00001.
        '''</summary>
        Friend Shared ReadOnly Property ErrorConexion() As String
            Get
                Return ResourceManager.GetString("ErrorConexion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00003.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCsv() As String
            Get
                Return ResourceManager.GetString("ErrorCsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x0000A.
        '''</summary>
        Friend Shared ReadOnly Property ErrorDelete() As String
            Get
                Return ResourceManager.GetString("ErrorDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00004.
        '''</summary>
        Friend Shared ReadOnly Property ErrorEscaneo() As String
            Get
                Return ResourceManager.GetString("ErrorEscaneo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0xFFFFF.
        '''</summary>
        Friend Shared ReadOnly Property ErrorEspecial() As String
            Get
                Return ResourceManager.GetString("ErrorEspecial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00005.
        '''</summary>
        Friend Shared ReadOnly Property ErrorGuardarDaño() As String
            Get
                Return ResourceManager.GetString("ErrorGuardarDaño", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00002.
        '''</summary>
        Friend Shared ReadOnly Property ErrorImportarVehiculos() As String
            Get
                Return ResourceManager.GetString("ErrorImportarVehiculos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00007.
        '''</summary>
        Friend Shared ReadOnly Property ErrorImpresionQR() As String
            Get
                Return ResourceManager.GetString("ErrorImpresionQR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0x00000.
        '''</summary>
        Friend Shared ReadOnly Property Example() As String
            Get
                Return ResourceManager.GetString("Example", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
